## Python Pandas In this we well see
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

Python Panda library  is very imp for data analyst ,data sceintst ,business analyst if you want to write any script ,want to play with data, play with csv file,excel file, json file, you can convert the dataset to data structure which we call dataframe and this type of datastructre is actually created by this panda library.

In [1]:
# Data frame is highly used in exploritory data analysis, feature engineering
# if we are able to read data from excel using panda library then data converts to data structure called dataframe
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
# Creating dataframe
df = pd.DataFrame(data = np.arange(0,20).reshape(5,4),index= ["Row1","Row2","Row3","Row4","Row5"],columns=["Column1",
                                                                                    "Column2","Column3","Column4"])
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [31]:
df.head()    #This will by default show you top five records

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [32]:
df.tail()   #This will by default show you last five records

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [34]:
df.head(2)  # We can pass parameters as in how many records you want to see

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [37]:
type(df)

pandas.core.frame.DataFrame

In [38]:
# Dataframe is one type of datastructure which we can create by using pandas library, this dataframe has many built in function
# which we can use to perform different kinds of operations for different purposes.

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [41]:
df.describe()   #This will only show column with interger of float type, object type will not be selected.

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

## Indexing
#  Indexing can be done by three techniques
1. Direct by using column name   # 
2. rowindex[loc]
3. rowindex columnindex [iloc]

In [43]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [46]:
#1. Direct By Column Name
# suppose i want to get data from column 1 and column 2

df[["Column1","Column2"]]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [49]:
# Suppose i want only data from single column suppose Column 4
df[['Column4']]   # note for single column we can use single list [], but for multiple coulmn always use nested i.e [[]]

Column4
Row1        3
Row2        7
Row3       11
Row4       15
Row5       19

In [53]:
print(type(df['Column4']))
print(type(df[['Column4']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [54]:
# Dataframe has multiple i.e more than one Row and Column but, Series can have either one row or One Column.

In [61]:
# 2. Rowindex[loc]
print(df.loc[['Row1','Row2']])
df.loc['Row1']

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7


Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [62]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [66]:
#3. Rowindex columnindex [iloc]
# suppose i wnat 12 13 16 17
df.iloc[3:5,0:2]

Column1  Column2
Row4       12       13
Row5       16       17

In [67]:
# suppose i wanna get 9 10 11 ,13 14 15, 17 18 19
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [70]:
## Converting dataframe into array use .values method of dataframe
df.iloc[2:,1:].values


array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [71]:
## 3. Basic Operations
df.isnull()    # Check if we have null value in our dataframe

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [73]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [79]:
# Suppose i want to check the count of each value in column4
df['Column4'].value_counts()

3     1
7     1
11    1
15    1
19    1
Name: Column4, dtype: int64

In [81]:
# Suppose i want to check the count of unique value in column4
df['Column4'].unique()

array([ 3,  7, 11, 15, 19])

In [83]:
df<2

Column1  Column2  Column3  Column4
Row1     True     True    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [86]:
df[df['Column2']>5]   # conditional indexing

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19