# NumPy

NumPy is a Python library.  
NumPy is used for working with arrays.  
NumPy is short for "Numerical Python".  
It also has functions for working in domain of linear algebra, fourier transform, and matrices. 
Fundamental package for scientific computing with python.

## Why Use NumPy?
In python list serve the purpose of array but are much slower   
NumPy provides an array object called 'ndArray' which has many function and is 50x faster than list   
Array is frequently used in DS where speed and resources matter a lot.  
NumPy is used in DS for ED:Exploratory Data analysis and Feature Engineering.


## Why is NumPy faster than list?
NumPy arrays are stored in continuous place in memory unlike lists so, processes can access and manipulate them efficiently.    
This behaviour is called locality of reference in CS. Also it is optimized to work with latest CPU architecture.

### Data Science (DS):  
Its a branck of CS Computer Science which study how to store,use and analyze data for deriving information from data.

In [11]:
import numpy
arr = numpy.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


## NumPy as np
Numpy is generally imported under np alias

In [14]:
import numpy as np  #Now the numpy package can be reffered as np insted of numpy
arr1 = np.array([23,45,65,87])
arr1

array([23, 45, 65, 87])

In [16]:
print(np.__version__)   #gets the version on numpy

1.23.3


### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray. 
We can create a NumPy ndarray object by using the array() function.

In [18]:
import numpy as np
myarray = np.array([12,23,45,56])
print(myarray)
print(type(myarray))

[12 23 45 56]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [21]:
# use a tuple to create an array
myar = np.array((1,2,3,4,5,6))
print(myar)
type(myar)

[1 2 3 4 5 6]


numpy.ndarray

In [37]:
# Shape method will return total no of rows and columnt in an array
myar.shape

(6,)

## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).
nested array: are arrays that have arrays as their elements.

### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [23]:
# Creat a 0D array 
import numpy as np
x0d = np.array(85)
print(type(x0d))
print(x0d)


<class 'numpy.ndarray'>
85


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [26]:
#Create a 1-D array containing the values 1,2,3,4,5:
x1d = np.array([1,2,3,4,5,6])
x1d



array([1, 2, 3, 4, 5, 6])

### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [41]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
a2d = np.array([[1,2,3],[4,5,6]])
print(a2d)
print(a2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.    
These are often used to represent a 3rd order tensor.

In [40]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values a,b,c and d,e,f:
import numpy as pb
a3d = pb.array([[['a','b','c'],['c','d','e']],[['a','b','c'],['c','d','e']]])
print(a3d)

[[['a' 'b' 'c']
  ['c' 'd' 'e']]

 [['a' 'b' 'c']
  ['c' 'd' 'e']]]


In [34]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
dim = a3d.ndim
print(dim)
dim = a2d.ndim
print(dim)


3
2


## Higher Dimensional Arrays
An array can have any number of dimensions.     
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [36]:
arr = pb.array([1,2,3,4],ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

## Array Indexing

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [57]:
import numpy as np
myarray = np.array([1,2,3,4,5])
# access 2nd element
print(myarray[1])
# access all element from 3rd position
print(myarray[2:])
# change 4th element of this array // hence array is also mutable
myarray[3] = 8
print(myarray)
# Access 2 elements from 3rd position
print(myarray[1:4]) # it will print 3 elemnts from position 1 i.e 4-1 = 3 element it ignores 4
# now i need to access last element then
print(myarray[-1]) # use -ve indexing to access an array from the end
# What if i want print all elements except the last one
print(myarray[:-1]) # i.e from all the element delete the last element

2
[3 4 5]
[1 2 3 8 5]
[2 3 8]
5
[1 2 3 8]


In [61]:
myarray = [1,2,3,4,5,6,7,8]
print(myarray[::])      # this will also print all the element
print(myarray[::-1])    # this will print the reversed array but actual array is not changed
print(myarray)
print(myarray[::-2])    # this will jump the two elemnts from last just like step function in vb

[1, 2, 3, 4, 5, 6, 7, 8]
[8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8]
[8, 6, 4, 2]


### Access 2-D Arrays       
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.     

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [72]:
import numpy as np
myarray2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myarray2d)

# Access the element on the 2nd row, 5th column:
x = myarray2d[0,4]
print(x)
# Access the element on the 2nd row, 5th column:
x =myarray2d[1,4]
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5
10


### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [85]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,5]
lst3 = [8,7,3,1,9]
myarray =  np.array([lst1,lst2,lst3])
print(myarray)
print("This is data requested" , myarray[:,1])  # getting 2nd row ':' this means all rows and ',1' means first column

[[1 2 3 4 5]
 [6 7 8 9 5]
 [8 7 3 1 9]]
This is data requested [2 7 7]


In [96]:
# now i want 7873
print(myarray[1:,1:3],"\n")

# get me 9519
print(myarray[1:,3:],"\n")

# Get me last two columns
print(myarray[:,3:],"\n")

# get me the shape of above 
print(myarray[:,3:].shape)

[[7 8]
 [7 3]] 

[[9 5]
 [1 9]] 

[[4 5]
 [9 5]
 [1 9]] 

(3, 2)


Array from EDA point of view

Exploratory Data Analysis (EDA) is an analysis approach that identifies general patterns in the data. These patterns include outliers and features of the data that might be unexpected. EDA is an important first step in any data analysis.

In [101]:
## EDA
myarray = np.array([1,2,3,4,5,0])
myarray<3    # this will check for each element in array and return boolean value

array([1, 2, 0])

In [102]:
# suppose i want to get the index then
myarray[myarray<3]    # this will return the elments less than 3. Cooool !! without using loop we are able to get elements

array([1, 2, 0])

In [109]:
myarray =  np.array([lst1,lst2,lst3])
print(myarray)
# suppose i want to reshape my array to 
myarray.shape    # this will print the current shape
myarray.reshape(5,3)   # we cannot reshape to 5,4 because then element will exceed i.e 5*4 = 20  but we have only 5*3 = 15 elements

[[1 2 3 4 5]
 [6 7 8 9 5]
 [8 7 3 1 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 8, 7],
       [3, 1, 9]])

In [118]:
# Methods to create an array
ar = np.arange(0,20,2)
print(ar)
ar.reshape(5,2)      # we can reshape it to mulit dimensional array

[ 0  2  4  6  8 10 12 14 16 18]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [120]:
# Operations on Array
print(ar)
ar*ar     # multiply array with itself

[ 0  2  4  6  8 10 12 14 16 18]


array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [123]:
print(myarray)
myarray*2

[[1 2 3 4 5]
 [6 7 8 9 5]
 [8 7 3 1 9]]


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 10],
       [16, 14,  6,  2, 18]])

In [135]:
print(np.zeros((3,4)))
#print(np.zeros_like((5,1)))
np.ones((4,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [198]:
np.random.randint(10,50)     # it will return a random value betwn 10 to 50

21

In [200]:
np.random.randint(10,50,5)    # it will initialze to size five

array([25, 41, 11, 49, 22])

In [208]:
# we can also reshape it
np.random.randint(10,50,6).reshape(3,2)

array([[40, 32],
       [25, 27],
       [22, 46]])

Standard Normal distribution (randn) = i.e., Mean will be zero and standard deviation will be 1

In [210]:
np.random.randn(2,2)

array([[ 1.00369133,  0.72943124],
       [ 2.17291466, -0.98006922]])

In [212]:
np.random.random_sample((2,2))    # return decimal values bewn 0 and 1

array([[0.19895154, 0.77063325],
       [0.00669614, 0.33930623]])